version: '2'
services:
  geoserver:
    image: kartoza/geoserver
    container_name: cmems_geoserver
    volumes:
      - ./shared_data/geoserver/data:/root/stores
      - ./shared_data/geoserver/geoserver_data_dir:/opt/geoserver/data_dir
      - ./shared_data:/shared
    expose:
      - 9090
  processors:
    image: planetek/cmems_processors:develop
    container_name: cmems_processors
    volumes:
      - ./shared_data/C5_OutputDir:/src/Processors/server/processors/C5_OutputDir
      - ./shared_data/C3_Input:/src/Processors/server/processors/C3_Input
    expose:
      - 9091
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=geonetwork
    container_name: cmems_postgres
    volumes:
      - ./shared_data/postgres/dump:/opt/data-volume
      - ./shared_data/postgres/data:/var/lib/postgresql/data
  geonetwork:
    image: geonetwork:postgres
    environment:
      - POSTGRES_DB_USERNAME=postgres
      - POSTGRES_DB_PASSWORD=geonetwork
    container_name: cmems_geonetwork
  esb:
    image: planetek/cmems_esb:develop
    container_name: cmems_esb
    volumes:
      - ./shared_data/geoserver/data:/root
      - ./shared_data/geoserver/geoserver_data_dir:/opt/geoserver/data_dir
      - ./shared_data:/shared
      - ./shared_data/.m2:/root/.m2
    expose:
      - 9190
  gui:
    image: planetek/cmems-gui:develop
    container_name: cmems_gui
    ports:
      - 80:8080
  mysql:
    image: mysql
    container_name: cmems_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cmems
      - MYSQL_DATABASE=cmems_activiti
      - MYSQL_USER=activiti
      - MYSQL_PASSWORD=pkz_029activiti
    volumes:
      - ./shared_data/mysql:/var/lib/mysql 
  activiti:
    container_name: cmems_activiti
    image: planetek/cmems_activiti:develop
    ports:
      - 9085:9085
    environment:
      - DB_TYPE=mysql  
      - DB_HOST=cmems_mysql
      - DB_NAME=cmems_activiti
      - DB_USER=activiti 
      - DB_PASS=pkz_029activiti
  nginx:
    container_name: cmems_nginx
    image: kyma/docker-nginx
    command: nginx
    volumes: 
      - ./shared_data/download:/var/www 
