version: '2'
services:
  processors:
    image: planetek/cmems_processors:develop
    ports:
      - 9091:9091
    container_name: cmems_processors
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=geonetwork
    container_name: cmems_postgres
  geonetwork:
    image: geonetwork:postgres
    environment:
      - POSTGRES_DB_USERNAME=postgres
      - POSTGRES_DB_PASSWORD=geonetwork
    container_name: cmems_geonetwork
    ports:
      - 8080:8080
  activiti:
    image: eternnoir/activiti:latest
    container_name: cmems_activiti
    ports:
      - 8085:8080
  geoserver:
    image: kartoza/geoserver
    container_name: cmems_geoserver
    ports:
      - 9090:8080
    volumes:
      - ./data:/root
      - ./geoserver_data_dir:/opt/geoserver/data_dir
  cmems_gui:
    image: planetek/cmems-gui:develop
    container_name: cmems_gui
    ports:
      - 6060:8080
