version: '3'
services:
  geoserver:
    image: kartoza/geoserver
    container_name: eosai_geoserver
    volumes:
      - ./shared_data/geoserver/geoserver_data_dir:/opt/geoserver/data_dir
      - ./shared_data:/shared
    expose:
      - 9090
  processors:
    image: planetek/eosai_processors:master
    container_name: eosai_processors
    volumes:
      - ./shared_data/C5_OutputDir:/src/Processors/server/processors/C5_OutputDir
      - ./shared_data/C3_Input:/src/Processors/server/processors/C3_Input
    expose:
      - 9091
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=geonetwork
    container_name: eosai_postgres
    volumes:
      - ./shared_data/postgres/datavolume:/opt/data-volume
      - ./shared_data/postgres/data:/var/lib/postgresql/data
  geonetwork:
    image: geonetwork:postgres
    environment:
      - POSTGRES_DB_USERNAME=postgres
      - POSTGRES_DB_PASSWORD=geonetwork
    container_name: eosai_geonetwork
  esb:
    image: planetek/eosai_esb:master
    container_name: eosai_esb
    volumes:
      - ./shared_data/geoserver/data:/root
      - ./shared_data/geoserver/geoserver_data_dir:/opt/geoserver/data_dir
      - ./shared_data:/shared
      - ./shared_data/.m2:/root/.m2
    expose:
      - 9190
  gui:
    image: planetek/eosai-gui:master
    container_name: eosai_gui
  mysql_activiti:
    image: mysql
    container_name: eosai_mysql_activiti
    environment:
      - MYSQL_ROOT_PASSWORD=cmems
      - MYSQL_DATABASE=cmems_activiti
      - MYSQL_USER=activiti
      - MYSQL_PASSWORD=pkz_029activiti
    volumes:
      - ./shared_data/mysql:/var/lib/mysql 
  activiti:
    container_name: eosai_activiti
    image: planetek/eosai_activiti:master
    expose:
      - 9085
    environment:
      - DB_TYPE=mysql  
      - DB_HOST=cmems_mysql_activiti
      - DB_NAME=cmems_activiti
      - DB_USER=activiti 
      - DB_PASS=pkz_029activiti
  manager_od:
    container_name: eosai_manager_od
    image: planetek/eosai_manager_od:master
    expose:
      - 8080
    volumes:
      - ./shared_data:/shared
  mysql_manager:
    image: mysql
    container_name: eosai_manager_mysql
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=cmems_manager
      - MYSQL_USER=cmems
      - MYSQL_PASSWORD=cmems
      - MYSQL_ROOT_PASSWORD=cmems
  postgres-cmems:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=cmems
      - POSTGRES_PASSWORD=cmems
      - POSTGRES_DB=CMEMS_DB
    container_name: eosai_db_api
    volumes:
      - ./init_cmems.sql:/docker-entrypoint-initdb.d/init.sql
      - ./shared_data/postgres-cmems/data:/var/lib/postgresql/data
  api:
    image: planetek/eosai_api:master
    container_name: eosai_api
  wordpress:
    container_name: eosai_wordpress
    image: wordpress
    expose:
      - 80
    environment:
      - WORDPRESS_DB_PASSWORD=SFzDmSz43aU0xhJ
      - WORDPRESS_DB_USER=cmems
    volumes:
      - wordpress_data:/var/www/html
  sftp:
    image: atmoz/sftp
    volumes:
      - wordpress_data:/home/cmems/data:rw
    ports:
      - "5427:22"
    container_name: eosai_sftp
    command: eosai:jVtwVN8AJHfnsX2B9Jya:1001
  mysql:
    container_name: eosai_wordpress_mysql
    image: mariadb
    environment:
      - MYSQL_USER=cmems
      - MYSQL_PASSWORD=SFzDmSz43aU0xhJ
      - MYSQL_ROOT_PASSWORD=lubHiOgCnFsRCT7
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./shared_data/mysql-wordpress:/var/lib/mysql
  portainer:
    container_name: eosai_portainer
    image: portainer/portainer
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock
      - ./shared_data/portainer:/data
    expose:
      -  9000
  proxy:
    ports:
      - 80:80
    image: planetek/eosai_proxy:base
    container_name: eosai_proxy
    volumes:
      - ./shared_data/download:/var/www/download
  backup:
    image: aveltens/wordpress-backup
    restart: always
    volumes:
      - ./shared_data/backups:/backups
      - wordpress_data:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_ENV_MYSQL_DATABASE=wordpress
      - MYSQL_ENV_MYSQL_USER=cmems
      - MYSQL_ENV_MYSQL_PASSWORD=SFzDmSz43aU0xhJ
      - MYSQL_PORT_3306_TCP_PORT=3306
    container_name: eosai_wordpress_backup
networks:
  default:
    external:
      name: eosai
volumes:
  wordpress_data:
