version: '3'
services:
  geoserver:
    image: kartoza/geoserver
    container_name: eosai_geoserver
    volumes:
      - ./shared_data/geoserver/geoserver_data_dir:/opt/geoserver/data_dir
      - ./shared_data:/shared
      - ./shared_data/geoserver/setenv.sh:/usr/local/tomcat/bin/setenv.sh
    expose:
      - 9090
  processors:
    image: dockerhub.planetek.it/pkz029_cmems_processors:master
    container_name: eosai_processors
    volumes:
      - ./shared_data/C5_OutputDir:/src/Processors/server/processors/C5_OutputDir
      - ./shared_data/C3_Input:/src/Processors/server/processors/C3_Input
    expose:
      - 9091
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=geonetwork
    container_name: eosai_postgres
    volumes:
      - ./shared_data/postgres/datavolume:/opt/data-volume
      - ./shared_data/postgres/data:/var/lib/postgresql/data
  geonetwork:
    image: geonetwork:postgres
    environment:
      - POSTGRES_DB_USERNAME=postgres
      - POSTGRES_DB_PASSWORD=geonetwork
    container_name: eosai_geonetwork
  esb:
    image: planetek/eosai_esb:master
    container_name: eosai_esb
    volumes:
      - ./shared_data/geoserver/data:/root
      - ./shared_data/geoserver/geoserver_data_dir:/opt/geoserver/data_dir
      - ./shared_data:/shared
      - ./datavolume:/opt/data-volume
      - ./shared_data/.m2:/root/.m2
    expose:
      - 9190
  gui:
    image: planetek/eosai-gui:master
    container_name: eosai_gui
  mysql_activiti:
    image: mysql
    container_name: eosai_mysql_activiti
    environment:
      - MYSQL_ROOT_PASSWORD=eosai
      - MYSQL_DATABASE=eosai_activiti
      - MYSQL_USER=activiti
      - MYSQL_PASSWORD=pkh_111activiti
    volumes:
      - ./shared_data/mysql_activiti:/var/lib/mysql 
  activiti:
    container_name: eosai_activiti
    image: planetek/eosai_activiti:master
    expose:
      - 9085
    environment:
      - DB_TYPE=mysql  
      - DB_HOST=mysql_activiti
      - DB_NAME=eosai_activiti
      - DB_USER=activiti 
      - DB_PASS=pkh_111activiti
  manager_od:
    container_name: eosai_manager_od
    image: dockerhub.planetek.it/pkh111_eosai_manager_od:master
    expose:
      - 8080
    volumes:
      - ./shared_data:/shared
  mysql_manager:
    image: mysql
    container_name: eosai_manager_mysql
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=eosai_manager
      - MYSQL_USER=eosai
      - MYSQL_PASSWORD=eosai
      - MYSQL_ROOT_PASSWORD=eosai
  postgres-eosai:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=eosai
      - POSTGRES_PASSWORD=eosai
      - POSTGRES_DB=EOSAI_DB
    container_name: eosai_db_api
    volumes:
      - ./init_eosai.sql:/docker-entrypoint-initdb.d/init.sql
      - ./shared_data/postgres-eosai/data:/var/lib/postgresql/data
  api:
    image: dockerhub.planetek.it/pkh111_eosai_api:master
    container_name: eosai_api
  proxy:
    ports:
      - 80:80
    image: planetek/eosai_proxy:base
    container_name: eosai_proxy
    volumes:
      - ./shared_data/download:/var/www/download
    restart: unless-stopped
networks:
  default:
    external:
      name: eosai
